In [10]:
import pandas as pd
df = pd.read_excel("/Users/mohammad/XAV/Departemant Media/porsline_cafe.xlsx")
df

,شناسه پاسخ دهنده,City,Gender,Age,Morning,Afternoon,Night,tasteful,اگر دوست داشتید، جمله‌هایی که به طرف مقابل می‌گویید، برای ما هم بنویسید.,Number,...,سرزنده و اجتماعی,مد روز و مدرن,کلاسیک و سنتی,آیا کافه‌ای هست که در گذشته وجود داشته و برای شما جالب بوده و امروز دیگر نیست؟,اگر یک روز به هر دلیلی بخواهید شهرتان را ترک کنید، برای کدام کافه بیشتر از همه دلتان تنگ می‌شود؟,اگر دوست دارید به ما بگویید که چرا دلتنگ این کافه می‌شوید؟,نام و نام خانوادگی,شماره موبایل,تاریخ شروع,تاریخ اتمام
0,vs1sB,بابل,زن,۱۸-۲۴,صبح تا ظهر,ظهر تا بعدازظهر,NaN,شیرینی سرا-امیر شکلات-میزبان,NaN,هفتگی,...,سرزنده و اجتماعی,NaN,NaN,برساو,لیلیوم,چون قرار های خیلیییی زیادی اونجا داشتم، دوستان...,NaN,NaN,1403/08/09-12:39:03,1403/08/09-12:45:40
1,iQndy,تهران,زن,۱۸-۲۴,صبح تا ظهر,ظهر تا بعدازظهر,NaN,نولان,همیشه قهوه‌ی خوب دارن، عالی نیست ولی واقعا خوب...,روزانه,...,NaN,NaN,NaN,آنتراکت و راستگو,امجدیه,NaN,یاسمن مومن پور,9.229698e+09,1403/08/09-10:51:58,1403/08/09-11:08:12
2,AdNgu,رشت,زن,۱۸-۲۴,NaN,ظهر تا بعدازظهر,NaN,قهوه ۲۹,یه جای کوچولو و دنجه ولی بچه هایی که اونجارو س...,هفتگی,...,NaN,مد روز و مدرن,NaN,کافه بابک,می جان,چون تمام میز و صندلی هاش تو پیاده رو هست و در ...,ماهور آزموده,9.211107e+09,1403/08/09-02:15:12,1403/08/09-02:27:09
3,dbwsG,تهران,زن,۲۵-۳۴,NaN,ظهر تا بعدازظهر,بعدازظهر تا شب,کایزن,NaN,روزانه,...,سرزنده و اجتماعی,NaN,NaN,NaN,NaN,NaN,نیکی مرادیان,9.383493e+09,1403/08/09-00:01:20,1403/08/09-00:07:10
4,RYReT,اصفهان,مرد,۳۵-۴۴,صبح تا ظهر,NaN,NaN,گندم کافی,NaN,روزانه,...,سرزنده و اجتماعی,NaN,کلاسیک و سنتی,NaN,خانه هولستر,چون با بهترین دوستام خیلی زیاد اونجا میریم و ب...,NaN,9.356133e+09,1403/08/08-23:44:51,1403/08/08-23:49:28
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
177,q8yGi,تهران,زن,۲۵-۳۴,صبح تا ظهر,ظهر تا بعدازظهر,NaN,وی کافه,NaN,هفتگی,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1403/08/07-17:57:02,1403/08/07-17:59:56
178,xSMBV,تهران,زن,۳۵-۴۴,صبح تا ظهر,ظهر تا بعدازظهر,NaN,مان,طعم متفاوتی از قهوه رو در کافه مان تجربه کردم ...,روزانه,...,NaN,NaN,NaN,آوانسن,کافه های مرکز شهر,NaN,NaN,NaN,1403/08/07-17:55:21,1403/08/07-17:59:42
179,bQMxO,تهران,زن,۱۸-۲۴,NaN,ظهر تا بعدازظهر,NaN,لوگغنیه,هم محیط اینجا خوبه هم قهوه اش,هفتگی,...,NaN,NaN,NaN,خیر,کافه بابل,چون خیلی قشنگههه یبار برید میدونید چی‌میگم,آتنا قبله و دی,9.212154e+09,1403/08/07-17:55:21,1403/08/07-17:58:46
180,pS5MR,کرج,مرد,۱۸-۲۴,صبح تا ظهر,NaN,NaN,سل,NaN,هفتگی,...,NaN,NaN,NaN,NaN,NaN,NaN,سینا منتظری,9.363280e+09,1403/08/07-17:55:21,1403/08/07-17:57:50
181,vzPsI,تهران,مرد,۲۵-۳۴,NaN,ظهر تا بعدازظهر,NaN,نولان,NaN,هفتگی,...,سرزنده و اجتماعی,NaN,NaN,شنف‌,امجدیه,NaN,آریا,9.359546e+09,1403/08/06-19:02:20,1403/08/06-19:07:31

In [12]:
tasteful_df = df[["City", "Gender","Age", "tasteful", "Number" ]]
tasteful_df

       City Gender    Age                      tasteful  Number
0     بابل      زن  ۱۸-۲۴  شیرینی سرا-امیر شکلات-میزبان   هفتگی
1     تهران     زن  ۱۸-۲۴                        نولان   روزانه
2       رشت     زن  ۱۸-۲۴                       قهوه ۲۹   هفتگی
3     تهران     زن  ۲۵-۳۴                        کایزن   روزانه
4    اصفهان    مرد  ۳۵-۴۴                     گندم کافی  روزانه
..      ...    ...    ...                           ...     ...
177   تهران     زن  ۲۵-۳۴                       وی کافه   هفتگی
178   تهران     زن  ۳۵-۴۴                          مان   روزانه
179   تهران     زن  ۱۸-۲۴                       لوگغنیه   هفتگی
180     کرج    مرد  ۱۸-۲۴                            سل   هفتگی
181   تهران    مرد  ۲۵-۳۴                         نولان   هفتگی

[182 rows x 5 columns]